import Navigation from "@/components/navigation/Navigation";
import "./globals.css";
// import "@fontsource/nunito-sans";
import "@fontsource/archivo-black";
import "@fontsource/lora";

import Footer from "@/components/footer/Footer";
import Topbar from "@/components/homepage/top-bar/Topbar";
import Copyright from "@/components/copyright/Copyright";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <div className="pb-6 sm:pb-8 lg:pb-12">
          <div className="mx-auto max-w-screen-2xl px-4 md:px-8">
            <Navigation />
            {children}
            <Footer />
          </div>
        </div>
        <Copyright />
      </body>
    </html>
  );
}
